### ISSUE TITLE
[2.3a] "empty" windows being created /w fullscreen

### ISSUE THREAD

**Issue by docwhat** [aquamacs-emacs/aquamacs-emacs#60] opened 2011-08-16 12:51 UTC
# My environment:

I have `one-buffer-one-frame` and tool-bar-mode turned off.  I have [ECB installed](http://docwhat.org/2011/08/aquamacs-2-3a-and-marmalade/).
# What happens:
- I start Aquamacs
- open a file in my Rails project
- run `ecb-activate`
- switch to another app using Alt-Tab
- switch back to Aquamacs using Alt-Tab

About 20% of the time, sometimes more, sometimes less, I get a new Window. It contains nothing and typing in the window doesn't work.  If I resize the window, then sometimes I get the modeline and it starts looking like yet-another-frame....sometimes with nothing in it or with an existing buffer in it.
# Notes:

I'm going to try disabling things, to see if I can come up with a more minimal set that causes the same problems.

**Comment by davidswelt** [comment] 2011-09-07 13:01
"Start Aquamacs without customizations" from the "Help/Diagnose and Report Bug" menu is your friend.

**Comment by docwhat** [comment] 2011-09-08 13:35
Hah...I was about to say I was unable to reproduce it without customizations, but it just happened...
1. I have Aquamacs on desktop 2 with a file open in it.  It is fullscreen (but I don't think that's needed, I saw this without full screen too).
2. I'm editing this bug on desktop 1.
3. I pressed command-tab to select to Aquamacs

...and a window opened on desktop 1 for aquamacs.  It was empty and had no modeline or anything.

What else can I do to help trouble shoot this?

**Comment by davidswelt** [comment] 2011-09-08 13:44
I can't reproduce this from your description.  Either I need to get 10.7 (don't have it yet for organizational reasons), or you need to give me a list of step-by-step instructions, starting with "Start Aquamacs without customizations" from the "Help/Diagnose and Report Bug" menu. 

Thanks
- David

## 

http://aquamacs.org -- Aquamacs: Emacs on Mac OS X
http://aquamacs.org/donate -- Could we help you? Return the favor and support the Aquamacs Project!

**Comment by docwhat** [comment] 2011-09-08 17:13
I'm guessing that it's a 10.7 thing because I don't remember seeing it before Lion.  Would it help if I bought you a copy of Lion?

This problem isn't something that happens each time, it can take many tries before it happens.  The two symptoms I've seen is:
1. When Command-Tabbing back to Aquamacs, none of the panes are active (the mode lines are grey) and when typing it takes a long time to get to the window, or never gets to the window.  Pressing command-tab twice (switch away and back) fixes that problem.
2. A new window opens that is missing the mode-line or any other content.  I can get content if I type emacs commands into it (C-x C-f for example). I usually just close the window (command-w).

More detailed steps:
1. "Start Aquamacs without customizations"
2. Open a file.
3. vertically split the window (C-c 3) and open another file in the other window (it does it without this, but this seems to make it more likely).
4. Bonus if you have more tabs, but I don't _think_ it changes the probability.
5. Command-tab to and from aquamacs.  Make sure you do work in both each time:
   1. Edit a file
   2. Save it.
   3. Command-Tab to the browser
   4. Command-R to reload it.
   5. Command-Tab to a command line.
   6. Type something
   7. Command-Tab to Aqumacs
   8. Repeat

I'm usually working on Rails when this happens. I bounce between the browser, my tests on the command line, and aquamacs.

I _suspect_ the problem is made worse by having more panes open in the window.  ECB is really good at triggering this problem, but I've seen it without ECB.

I hope that helps.

**Comment by davidswelt** [comment] 2011-09-19 21:26
So far I haven't been able to reproduce this with Lion, neither in Aquamacs 2.3 nor in Aquamacs 3.x.

Empty frames are created internally sometimes (e.g., multiple Spaces), but they should not be visible to the user (that's where the bug is).  It doesn't seem like a Lion thing to me - much rather an ECB incompatibility.

**Comment by docwhat** [comment] 2011-09-20 12:51
Hmm....but that doesn't explain why I can recreate this with "Start Aquamacs without customizations".

Is there some kind of debugging I could do?  Like turning on tracing or something somewhere in the code?

**Comment by davidswelt** [comment] 2011-09-20 12:59
Right. 

As for replication of the problem, you'd have to find a minimal case and note exactly what you're doing.  How you open files, what actions you do.  You want to reduce this to a small set of steps - it becomes tedious otherwise.

Second, to do some debugging, have a look at one-buffer-one-frame.el and instrument the functions there.  It creates _empty_ frames, and I suspect this is what you're seeing - but you'll find out if you experiment with OBOF.  The code there runs whether or not obof-mode or tabbar-mdoe are on, but it interacts with those. Commenting out some things (e.g., _empty_ frame creation) may help diagnose the problem.

**Comment by davidswelt** [comment] 2011-12-21 15:08
I have now seen this problem every now and then, but do not know how to reproduce it.
Do you have any additional information?

**Comment by docwhat** [comment] 2011-12-21 15:11
I'm sorry. I wish I did.  If you have some specific steps I should use to once I have recreated it, I can try them.  Otherwise, maybe we could do a desktop sharing session so you can debug it on my system remotely?

You can reach me via any of my alter-egos on http://docwhat.org/ if you want to try that.

**Comment by roryk** [comment] 2012-03-06 19:00
I have this exact issue as well. I can induce it if I start with no customizations and go into fullscreen and then alt-tab away and back a couple of times.

**Comment by davidswelt** [comment] 2012-03-11 13:03
Please try the nightly build of the Aquamacs 2.x series at http://aquamacs.org/nightlies.shtml
The fullscreen mode has been revised.

**Comment by roryk** [comment] 2012-03-23 23:29
Thank you for responding David-- this actually makes the problem a little bit worse. Now instead of spawning a new mini-frame randomly it spawns a new full size frame. This occurs if I start it with no customizations as well.

**Comment by roryk** [comment] 2012-03-28 01:20
Okay I have narrowed this down a little bit more. Aquamacs does not have to be in full screen mode. If you alt-tab to an application that is in full screen mode and tab back though, then Aquamacs will sometimes spawn a new frame in a new window. If you alt-tab to other applications not in full screen mode it does not seem to happen. I just alt-tabbed to chrome and to aquamacs, neither of which are in full screen mode 30 times in a row without the new window popping up. alt-tabbing to iterm (which is full screen) and back to aquamacs (still not in full screen) popped open the new empty frame in 4 tries.

**Comment by roryk** [comment] 2012-03-28 01:25
Just to add some more data to confirm it is a problem alt-tabbing back from an app in full screen mode to aquamacs. If I un-fullscreen iterm it does not happen. If I fullscreen chrome and alt-tab back and forth to non-fullscreened aquamacs it happens. If I fullscreen Aquamacs and alt-tab back and forth to a non-fullscreen iTerm it also happens. So alt-tabbing either from or to Aquamacs if a) the application you are alt-tabbing from is fullscreen or b) if Aquamacs is fullscreen, causes this phantom-frame-in-a-new-window to be created.

**Comment by milanmitrovic** [comment] 2012-04-16 12:45
I just want to add that I am suffering the same issue and it is very annoying...

**Comment by davidswelt** [comment] 2012-04-18 11:58
Rory,
I can't reproduce this from your description.  Here's what I do, in Aquamacs 2.x (current build), on Lion:

Help->Diagnose->Start w/o customizations
Switch to Chrome via Dock and full-screen the window
Alt-Tab back to new Aquamacs instance
(Now I have a window showing an empty _scratch_ buffer.  The window is grey, but I can type.)
Alt-Tab to Chrome.
(Now I have the Chrome menu bar, but I am not in the screen with the fullscreen window.)
(Optional: switch to screen with fullscreen window with Ctrl-Right)
Alt-Tab to Aquamacs.
I'm back at my single Aquamacs window, ready to accept input.  Nothing unexpected happens.

I couldn't get it with iTerm2 either...

**Comment by roryk** [comment] 2012-04-18 13:38
Hi David! Thanks for the reply. You are correct, I could not reproduce it either starting without customizations anymore, I am ot sure what is different. However I could reproduce it every time by doing this:

Start w/o customizations
Full Screen Aquamacs
_vertically split the window with ^X-3_
alt-tab back and forth to another application and back several times.

It also occurs if I do the same steps but instead of full screening Aquamacs, split the window vertically, full screen another application and then alt-tab back and forth.

Both of these make a new frame called "Aquamacs" come up in Window->Frames.

Thanks!

**Comment by docwhat** [comment] 2012-04-18 14:48
I can confirm that Aquamacs 2.4 on Lion 10.7.3, my instructions in comment #5 still work.  It took me about 5 minutes of simulating an "edit file, reload browser to view changes, repeat" to reproduce it. As @roryk says, it's very important that you split a window.  I'm not sure why.

The only addition I'd add to the instructions is that the browser needs to be on one desktop while emacs in Full Screen Mode (command-control-F) should be in another.

I wonder if it is in part due to the time it takes to switch desktops? In Lion, the time to switch desktops is longer due to the animation.  What makes me think that is that the Aquamacs frame appears on the desktop I'm switching from not the desktop I'm switching to.

Ciao!

**Comment by davidswelt** [comment] 2012-04-18 20:41
I think I just got somewhere.

I still can't reproduce directly from your description, but docwhat's idea regarding the desktop switch time may be a good hint.

What sort of hardware are you guys running?  It could be that your animation takes more time than mine.
Try evaluating this code:

(defun aquamacs-handle-app-activated ()
  "Aquamacs has been activated.
Ensure that there is a (hidden) frame in the current space."
  (interactive)
  (run-with-idle-timer 1.0 nil 'aquamacs-handle-app-activated2))

This doubles the time Aquamacs gives the animation to finish (from half a second in version 2.4).

**Comment by docwhat** [comment] 2012-04-18 21:01
I tried setting it to `3.0` and I still get it....

I think I found a new way to reproduce it:
- fullscreen emacs on another desktop.
- open buffers as above.
- edit something, save.
- command-tab to switch to browser (or whatever) on another desktop.
- command-tab switch back and immediately press ^X or any other control sequence.

It's as if the focus is in the wrong place, which causes Aquamacs to open a new frame to accept the key sequence?

Dunno.

**Comment by docwhat** [comment] 2012-04-18 21:01
BTW: Speed of commands seems to play a part in this.  I'm probably typing faster than something somewhere is expecting it.

**Comment by roryk** [comment] 2012-04-18 21:31
Hi David,

I'm running the older 2.4 GhZ Intel Core 2 Duo Macbook with 4 gigs of RAM. Your fix seems to have fixed it a little bit but I still have been able to induce it, it just takes a lot longer, even bumping it up to 2.0. For some reason it seems like if I just let Aquamacs sit for a while and then switch over to it, it happens, instead of being able to alt-tab back and forth a couple of times and induce it. I opened Aquamacs in no customizations mode, full-screened, split the screen and evaled your fix.

The other thing that I just noticed is that if alt-tab twice really fast, it won't switch me back to the only open frame in Aquamacs but it does switch my focus. It doesn't induce the new window to form though. Not sure if those two things are related at all.

**Comment by roryk** [comment] 2012-04-18 21:40
The other thing is that if the new window spawns and I switch to it and close it, it spawns a new frame. It will keep spawning those new frames for a while as I close them until I pick the wrong frame from the Window->Frames menu and I go back to the full screen frame in Aquamacs. Then the new frame just disappears and the Window-Frames is greyed out since there is just the one, it is like the new frame just disappeared. I think if I never went back to the full screen frame it would open new frames forever.

Also sometimes it looks like a new frame opens up, like Lion does the new frame opening animation, but then when I look in Window->Frames there is no new frame. Usually sometime soon after that I can get the new frame to actually spawn by alt-tabbing back and forth.

Sorry for the useless information, it is intermittent now and I haven't figure out a way to cause it every time with your fix.

**Comment by davidswelt** [comment] 2012-04-22 23:20
I think I know what is happening, and it has to do with the speed of your animation and with which frames are active while the animation is running.

Try evaluating the following - this should take care at least of cases when Aquamacs is showing a full-screen window.

(defun aquamacs-handle-app-activated2 ()
  (unless (or (ns-frame-is-on-active-space-p (selected-frame))
          (eq (frame-parameter nil 'fullscreen) 'fullboth))
    ;; find a frame on active space
    ;; (unless (ns-visible-frame-list)
      (let\* ((display-buffer-reuse-frames 'select)
       (one-buffer-one-frame nil)
       (hf (aquamacs-make-empty-frame aquamacs-deleted-frame-position)))
      (select-window (frame-first-window hf))
      (make-frame-visible hf) ; HACK: must do this first, presumably to convince NS to make it key.
      ;; (switch-to-buffer (init-aquamacs-last-frame-empty-buffer) 'norecord)
      (make-frame-invisible hf t))))

**Comment by docwhat** [comment] 2012-04-23 02:10
Okay, that looks promising. I can't reproduce the extra frame after a couple minutes of trying.

Of course, since I couldn't reproduce this 100% of the time, I can't be positive.  But usually I can make it happen once after a couple of minutes.  Switching quickly would usually produce results quickly.

All in all, I say good job!

Ciao!

**Comment by roryk** [comment] 2012-04-23 19:00
David,

I've been using it all day with your fix and haven't had a phantom frame pop up. I think you nailed it; I'll post again on Friday and say if I have seen the behavior by then as well.

Thanks! This was super annoying.

**Comment by roryk** [comment] 2012-04-26 17:33
I know I said Friday but I have been using it constantly for the past three days and your fix seems to have completely fixed it.

**Comment by davidswelt** [comment] 2012-04-27 01:50
Good, thanks for letting me know.  I'll close this issue now.

**Closed as completed by davidswelt** 2012-04-27 01:50 UTC
Labels: more info requested

**Comment by roryk** [comment] 2012-05-09 19:42
I can force this behavior to occur using the command line tools. If I have a session open and I run aquamacs on a file from the command line, it opens a new full sized window rather than opening it in the window already created, even with show buffers in new frames unchecked.
