### ISSUE TITLE
Failed to initialize color list unarchiver: Error Domain=NSCocoaErrorDomain Code=4864

### ISSUE THREAD

**Issue by max-arnold** [aquamacs-emacs/aquamacs-emacs#142] opened 2018-10-17 07:35 UTC
Moving this off the mailing list.  The error below happens on Mac OS Mojave when Aquamacs starts.  Also, `customize-face` color selector and `list-color-display` function are broken (they both result in the "Wrong number of arguments: max, 0" error message).

```
2018-10-17 14:13:31.599 Aquamacs[2854:2569278] Failed to initialize color list unarchiver: Error Domain=NSCocoaErrorDomain Code=4864 "*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: non-keyed archive cannot be decoded by NSKeyedUnarchiver" UserInfo={NSDebugDescription=*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: non-keyed archive cannot be decoded by NSKeyedUnarchiver}
```

It happens even if I remove the `~/Library/Colors/Aquamacs.clr` as suggested here https://lists.gnu.org/archive/html/emacs-devel/2018-09/msg00932.html

Tested on the latest nigthly build:

```
Aquamacs/vanilla  GNU Emacs 25.3.50.1 (x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511))
dated 2018-10-17 rev. a8f0c20ba68e2e95a83afe8125d65286019425f2
```

This **does not** happen with Aquamacs binary compiled on my machine:

```
Aquamacs/vanilla  GNU Emacs 25.3.50.1 (x86_64-apple-darwin18.0.0, NS appkit-1671.00 Version 10.14 (Build 18A391))
dated 2018-10-17 rev. a8f0c20ba68e2e95a83afe8125d65286019425f2
```

The obvious difference is Xcode/SDK version:

```
% xcodebuild -version
Xcode 10.0
Build version 10A255
```

```
% xcodebuild -showsdks | grep mac
macOS SDKs:
	macOS 10.14                   	-sdk macosx10.14
```

I also have Macports installed, may be the build picks up some libraries form /opt/local.

**Comment by nega0** [comment] 2019-02-12 15:22
This bug was imported from Emacs. For some commentary see https://debbugs.gnu.org/cgi/bugreport.cgi?bug=33713 and (the merged bug) https://debbugs.gnu.org/cgi/bugreport.cgi?bug=33833. 

It's claimed to be fixed in "Emacs 26.2", but I couldn't find the fixes in their git, nor have I tried to build it.

**Comment by davidswelt** [comment] 2019-07-26 08:29
Reproducing this with builds from watson, but not with local builds.

watson:~ dr$ xcodebuild -showsdks | grep mac
macOS SDKs:
	macOS 10.13                   	-sdk macosx10.13

Debugger entered--Lisp error: (wrong-number-of-arguments max 0)
  max()
  apply(max nil)
  list-colors-print((("alternateSelectedControlColor") ("alternateSelectedControlTextColor" "controlColor" "controlBackgroundColor") ("controlDarkShadowColor" "controlShadowColor" "controlLightHighlightColor" "controlHighlightColor") ("controlTextColor" "disabledControlTextColor") ("gridColor") ("headerColor") ("headerTextColor") ("highlightColor") ("keyboardFocusIndicatorColor") ("knobColor") ("labelColor" "quaternaryLabelColor") ("scrollBarColor") ("secondaryLabelColor") ("secondarySelectedControlColor") ("selectedControlColor") ("selectedControlTextColor") ("selectedKnobColor" "selectedMenuItemColor") ("selectedMenuItemTextColor") ("selectedTextBackgroundColor") ("selectedTextColor") ("shadowColor") ("tertiaryLabelColor") ("textBackgroundColor") ("textColor") ("windowBackgroundColor") ("windowFrameColor") ("windowFrameTextColor" "Black") ("Blue") ("Brown") ("Cyan") ("Green") ("Magenta") ("Orange") ("Purple") ("Red") ("Yellow") ("White")) nil)
  list-colors-display()
  funcall-interactively(list-colors-display)
  call-interactively(list-colors-display record nil)
  command-execute(list-colors-display record)
  execute-extended-command(nil "list-colors-display" "list-color")
  funcall-interactively(execute-extended-command nil "list-colors-display" "list-color")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

**Comment by davidswelt** [comment] 2019-07-26 13:09
Sorry this has taken me a while to investigate.  The reason is not the SDK version but the operating system it is built on, because much GNU Emacs code assumes the binary is built in the runtime environment.  The list of colors changed between MacOS versions, as it seems, and some special colors are no longer available under their old names.
I have checked in a fix.

**Comment by nega0** [comment] 2019-08-21 19:00
`(list-colors-display)` is still broken. Looks like `(defined-colors)` is still returning the incomplete color list with the erroneous `nil`.

```
Debugger entered--Lisp error: (wrong-number-of-arguments max 0)
  max()
  apply(max nil)
  list-colors-print((("alternateSelectedControlColor") ("alternateSelectedControlTextColor" "controlColor" "controlBackgroundColor") ("controlDarkShadowColor" "controlShadowColor" "controlLightHighlightColor" "controlHighlightColor") ("controlTextColor" "disabledControlTextColor") ("gridColor") ("headerColor") ("headerTextColor") ("highlightColor") ("keyboardFocusIndicatorColor") ("knobColor") ("labelColor" "quaternaryLabelColor") ("scrollBarColor") ("secondaryLabelColor") ("secondarySelectedControlColor") ("selectedControlColor") ("selectedControlTextColor") ("selectedKnobColor" "selectedMenuItemColor") ("selectedMenuItemTextColor") ("selectedTextBackgroundColor") ("selectedTextColor") ("shadowColor") ("tertiaryLabelColor") ("textBackgroundColor") ("textColor") ("windowBackgroundColor") ("windowFrameColor") ("windowFrameTextColor" "Black") ("Blue") ("Brown") ("Cyan") ("Green") ("Magenta") ("Orange") ("Purple") ("Red") ("Yellow") ("White")) nil)
  list-colors-display()
  eval((list-colors-display) nil)
  elisp--eval-last-sexp(t)
  eval-last-sexp(t)
  eval-print-last-sexp(nil)
  funcall-interactively(eval-print-last-sexp nil)
  call-interactively(eval-print-last-sexp nil nil)
  command-execute(eval-print-last-sexp)
```

**Comment by davidswelt** [comment] 2019-08-21 19:13
Ah gee, don’t know what happened there, sorry.  I hope it’ll get looked at for the next version.

**Comment by treese** [comment] 2019-08-21 20:53
@nega0 Looks like the earlier patch was on the right track, and I think the byte-compiler wiped it out. Try redefining `xw-defined-colors` like this:
```
(defun xw-defined-colors (&optional frame)
  "Internal function called by `defined-colors', which see."
  (if (featurep 'ns)
      (ns-list-colors)
    (or frame (setq frame (selected-frame)))
    (let (defined-colors)
      (dolist (this-color (if (eq system-type 'windows-nt)
			      (or (mapcar 'car w32-color-map) x-colors)
			    x-colors))
	(and (color-supported-p this-color frame t)
	     (setq defined-colors (cons this-color defined-colors))))
      defined-colors)))
```
If that works, I'll commit the change.

**Comment by max-arnold** [comment] 2019-09-27 04:52
@treese Your patch works for me, thanks!

**Comment by treese** [comment] 2019-09-27 14:17
Glad to hear it. I'll add the patch to the main code, so I'm leaving this open until I do that.

**Comment by treese** [comment] 2019-09-28 01:13
Patched in commit 9a1635f307

**Comment by treese** [comment] 2020-03-23 16:00
This is still lingering in current Aquamacs versions, so I'm reopening this to make sure we get the fix in as we roll up to newer Emacs releases.

**Comment by treese** [comment] 2020-12-30 01:16
Somehow this wasn't in 3.5, but it is at least in the current nightly builds for the upcoming 3.6.

**Closed as completed by treese** 2020-12-30 01:16 UTC
