### ISSUE TITLE
The info directory listing is messed up

### ISSUE THREAD

**Issue by kaofelix** [aquamacs-emacs/aquamacs-emacs#9] opened 2010-03-24 17:37 UTC
When doing an M-x info on Aquamacs the directory shows almost every info manual link under the "Emacs" title. Under the list some other titles appear empty: GNU Emacs Lisp, Emacs editing modes, Emacs network features, Emacs misc features, and Emacs lisp libraries. When I open the dir file it reflects the same structure shown on the info directory (empty titles bellow everything else). 

Strangely, the dir file (http://github.com/davidswelt/aquamacs-emacs/blob/master/info/dir) on the git source tree shows what appears to be the right organization. I've manually replaced it on the Aquamacs package and now the empty titles disappear, but everything still shows under the Emacs title. My guess is that Emacs is building the info directory based on the DIR-SECTION specified on each info file. For instance, the elisp-1.gz info file have the following directive:

INFO-DIR-SECTION Emacs

when it probably should be

INFO-DIR-SECTION GNU Emacs Lisp

**Comment by davidswelt** [comment] 2010-03-24 21:12
Sounds like a good explanation, but I also don't understand where the extra headlines come from: I don't see them in my private build. 

If you look into the function `Info-insert-dir', you see that the "dir" file is not taken verbatim to form the directory node.  
If you (setq Info-dir-contents nil), and then press "d" in the *info* buffer, it should update the contents.  Now, when I comment out the call to`(Info-dir-remove-duplicates)', I get nicer results along the lines of what you'd like to see.

That's about how much I've found out about it - the info package is pretty convoluted.  
Feel free to play around with it and maybe we can pinpoint the problem.

**Comment by davidswelt** [comment] 2010-03-24 21:23
See also the variable `Info-streamline-headings'.  It seems like it's behaving as intended w.r.t. the merging of all those categories.  I don't know why.

I don't have a handle on the extra categories at the end.

**Comment by davidswelt** [comment] 2010-03-26 11:43
The following commit should allow the info mode to show system-wide info files:

commit fe07563f3931968ddecb4f9605ddbee953f14935
Author: David Reitter david.reitter@gmail.com
Date:   Thu Mar 25 12:22:45 2010 -0400

```
ensure Info-default-directory-list contains system-level info files as well
force re-initialization of Info-directory-list by the next `info-initialize'.
clear "INFOPATH" environment variable (if set by nsterm.m).
```

**Comment by kaofelix** [comment] 2010-04-12 20:15
Hey david, sorry for the long time without answering to that. The commit you mention really made emacs find my system wide info files. The empty headers I've mentioned are still there though. I'll try to play with the info system a little bit and try to pinpoint the issue like you suggested.

**Comment by davidswelt** [comment] 2010-05-15 23:30
This works for me now.  Is it still a problem for you (2.0), or can we close this?

**Comment by davidswelt** [comment] 2010-05-25 03:02
Kao, is this OK now?

**Comment by kaofelix** [comment] 2010-05-27 12:34
David, sorry for taking so long to answer to this. I'm still having some problems with this. I spent some time trying to figure out why this happens, but I had not come to a conclusion yet. I'll try to give you more details on this matter ASAP.

**Comment by treese** [comment] 2019-02-05 03:53
Looking at old bugs: the Info directory seems to be fine now.

**Closed as completed** 2019-02-07 04:02 UTC
