### ISSUE TITLE
<S-tab> is translated to ^Y, should be to <backtab>

### ISSUE THREAD

**Issue by gracjan** [aquamacs-emacs/aquamacs-emacs#68] opened 2012-05-21 20:45 UTC
Here is what I get after describe-key and pressing SHIFT-TAB:

^Y (translated from <S-tab>) runs the command cua-paste, which is an
interactive compiled Lisp function in `cua-base.el'.

It is bound to ^V, ^Y, <S-insertchar>, <S-insert>, <menu-bar> <edit>
<paste>.

(cua-paste ARG)

I do not want SHIFT-TAB to be translated. How to prevent it? Why is it translated at all?

Linux version of Emacs recognizes SHIFT-TAB as BACKTAB.

I need BACKTAB to perform unindent.

More info:

Aquamacs is a distribution of GNU Emacs that is adapted for Mac users.

GNU Emacs 23.3.50.1 (i386-apple-darwin9.8.0, NS apple-appkit-949.54)
 of 2011-10-25 on braeburn.aquamacs.org - Aquamacs Distribution 2.4

Mac OS X 10.7.3.

**Comment by davidswelt** [comment] 2013-02-15 03:29
Can't reproduce.  describe-key S-Tab gives me this message, both in Aquamacs 2.5 and in 3.x:

<backtab> (translated from <S-tab>) is undefined

Could you start without customizations (Help/Diagnose menu) and try again?

**Comment by gracjan** [comment] 2014-05-31 05:39
This seems to have been fixed, works in 30a.

**Comment by treese** [comment] 2020-09-09 20:26
Previously noted as fixed, so closing.

**Closed as completed** 2020-09-09 20:31 UTC
