### ISSUE TITLE
R-Mode / comint / encoding

### ISSUE THREAD

**Issue by davidswelt** [aquamacs-emacs/aquamacs-emacs#53] opened 2011-03-17 12:19 UTC
Begin forwarded message:

From: Jean-Baptiste Lepetit jeanbaptiste.lepetit@gmail.com
Date: March 8, 2011 3:37:58 AM EST
To: aquamacs-bugs@aquamacs.org
Subject: [Aquamacs-bugs] Communication between aquamacs and the terminal/R console
Reply-To: Bug reports for Aquamacs Emacs aquamacs-bugs@aquamacs.org

Hi,
I found out on forums that I wasn't alone with this problem, but couldn't find a proper answer.
When I launch a .R file with aquamacs, it messes up all the French accents in the script editor. I've tried to change encoding to latin-1, utf-8, etc, and to switch language to French, without any success so far. Strangely, I can manually replace the wrongly encoded characters, by re-typing them, since they then appear correctly.
However, when I launch the R console, none of the accents work on output. I get outputs like :

x<-"répété"
x
[1] "r\303\251p\303\251t\303\251"

and characters like "é", are also replaced by 'e

It's doesn't work either if I launch R from the terminal INSIDE emacs (M-x shell, then r).
If I launch R from the Terminal app, or from the built-in R console, everything works perfectly.

**Comment by treese** [comment] 2020-09-09 20:31
This is quite old, and I can't reproduce it now, so closing.

**Closed as completed by treese** 2020-09-09 20:31 UTC
Labels: Unreproducible
