### ISSUE TITLE
Aquamacs hangs when deleting an XML comment

### ISSUE THREAD

**Issue by martinfowler** [aquamacs-emacs/aquamacs-emacs#93] opened 2014-01-08 21:08 UTC
When editing an XML document, deleting the opening of an XML comment causes Aquamacs to hang. 

The hang may occur after 10-20 seconds. When it does one processor gets pegged to 100% and Aquamacs is unresponsive. Only thing to do is Force Quit.

On investigation I found this happens when I'm in nxml mode and also in flyspell mode. (My speculation is that it's flyspell's activity that's triggering the hang.) If I go out of flyspell mode before performing the edit then the hang does not happen.

**Comment by davidswelt** [comment] 2014-01-08 21:12
Flyspell-mode seems to be necessary.

I reproduce the hang when enabling flyspell-mode, and doing flyspell-buffer in addition to that.

The next step would be to see if this reproduces in plain GNU Emacs.

**Comment by martinfowler** [comment] 2014-01-23 23:02
So I tried to reproduce it in GNU Emacs today, and found I could no longer reproduce it in Aquamacs. I don't know what changed.

**Comment by davidswelt** [comment] 2016-06-16 03:20
Closing this issue as it no longer reproduces.

**Closed as completed by davidswelt** 2016-06-16 03:20 UTC
