### ISSUE TITLE
dedicated windows / switching by menu

### ISSUE THREAD

**Issue by davidswelt** [aquamacs-emacs/aquamacs-emacs#63] opened 2012-01-13 02:19 UTC
Another, more serious problem is that 2.4 has difficulties in switching between buffers that are on different frames. One instance can be reproduced as follows. Start 2.4 without customizations. Turn "Show Tabs" off and turn "Show Buffers in New Frames" on. Then in the Window menu select "Messages" which leads the Messages buffer to open in a new frame, which becomes the active frame. Now in the Window menu, do "Select Next Buffer" or do "Select Previous Buffer". However, the frame with the Message buffer remains active, and an error message appears saying "ad-Orig-error: Window #<window 9 on *Messages*> is dedicated to buffer _Messages_". The same happens with "M-x next buffer"

**Comment by davidswelt** [comment] 2012-01-13 02:19
As a supplement of what I wrote below: Apparently, in 2.4 the command  "next-buffer" has not anymore the power as in 2.3. What, in 2.4, is that command which does what "next-buffer" does in 2.3? I would like to know this for adjusting the code in my preferences.el to 2.4
(Konrad Podzeck)

**Comment by davidswelt** [comment] 2012-01-13 19:57
Konrad, I can't consistently reproduce it.  I've seen it once, but now this has gone away and works as designed (testing with current 2.x code). Please advise.

**Comment by podczeck** [comment] 2012-01-16 20:50
David,

even with the recent nightly,I can still consistently reproduce  it with the steps described in my original, which in particular involve: Turn "Show Tabs" off and turn "Show Buffers in New Frames" on. 

Konrad

Am 13.01.2012 um 20:57 schrieb David Reitter:

**Comment by podczeck** [comment] 2012-01-17 00:11
As a supplement to my previous mail, because you speak of "current 2.x code", I meant 3.x code (Aquamacs 2.4). 

Am 13.01.2012 um 20:57 schrieb David Reitter:

**Comment by davidswelt** [comment] 2012-01-17 00:28
On Jan 16, 2012, at 7:11 PM, podczeck wrote:

> As a supplement to my previous mail, because you speak of "current 2.x code", I meant 3.x code (Aquamacs 2.4). 

Now I'm completely confused.

If you mean 3.x code, why are you saying Aquamacs 2.4?????

**Comment by podczeck** [comment] 2012-01-17 00:30
Am 17.01.2012 um 01:28 schrieb David Reitter:

> On Jan 16, 2012, at 7:11 PM, podczeck wrote:
> 
> > As a supplement to my previous mail, because you speak of "current 2.x code", I meant 3.x code (Aquamacs 2.4). 
> 
> Now I'm completely confused.
> 
> If you mean 3.x code, why are you saying Aquamacs 2.4?????

Just following the terminology from your web page, nightly builds section:

Aquamacs 3.x (Emacs 24, Cocoa-based, Intel, "aquamacs24" branch)

**Comment by davidswelt** [comment] 2012-01-17 00:38
On Jan 16, 2012, at 7:30 PM, podczeck wrote:

> Am 17.01.2012 um 01:28 schrieb David Reitter:
> 
> > On Jan 16, 2012, at 7:11 PM, podczeck wrote:
> > 
> > > As a supplement to my previous mail, because you speak of "current 2.x code", I meant 3.x code (Aquamacs 2.4). 
> > 
> > Now I'm completely confused.
> > 
> > If you mean 3.x code, why are you saying Aquamacs 2.4?????
> 
> Just following the terminology from your web page, nightly builds section:
> 
> Aquamacs 3.x (Emacs 24, Cocoa-based, Intel, "aquamacs24" branch)

OK, that would be Aquamacs 3.x, and not the latest release, Aquamacs 2.4.

Aquamacs 2.4 is the release in the Aquamacs 2.x series, which is based on Emacs 23.

So you really mean the 3.x nightly build, and not the release.  I'll try again with that.

**Comment by podczeck** [comment] 2012-01-17 00:59
I see. Sorry, I have misunderstood  you thread "Aquamacs 2.4 adoption". The three points I made initially:

-- Scrolling with the mouse wheel is rather bumpy (holprig) with long buffers, in particular when linum mode is on;

-- Smart spacing does not work when pasting by using mouse 2;

-- It is not possible to insert "flexible white space" in the auctex toolbar via drag and drop;

and, subsequently, concerning "next-buffer" all concern the 3.x code. Code 2.x, including the 2.4 release,  works fine in all these four respects.  Sorry once more, I misinterpreted your opening of that thread as saying you would like more people using the 3.x code to get more testing, misunderstanding 24 as a synonym fo 3.x.

Konrad

Am 17.01.2012 um 01:38 schrieb David Reitter:

**Comment by davidswelt** [comment] 2012-01-17 01:06
well that's good then, I need more 3.x bug reports!

**Comment by davidswelt** [comment] 2012-01-19 02:57
OK, just looking into this (and I reproduce it again).

The semantics of `next-buffer' have changed from Emacs 23 to Emacs 24.  In 23, they were "Switch to the next buffer in cyclic order." 
In 24, they are "In selected window switch to next buffer."

And the code does this.

Perhaps we need to bind these menu items to something more useful in Aquamacs.

**Comment by podczeck** [comment] 2012-01-19 12:54
Am 19.01.2012 um 03:57 schrieb David Reitter:

> OK, just looking into this (and I reproduce it again).
> 
> The semantics of `next-buffer' have changed from Emacs 23 to Emacs 24.  In 23, they were "Switch to the next buffer in cyclic order." 
> In 24, they are "In selected window switch to next buffer."
> 
> And the code does this.
> 
> Perhaps we need to bind these menu items to something more useful in Aquamacs.

One possibility could be to replace

(defun next-tab-or-buffer ()
  "Call (tabbar-forward) if tabbar-mode is on; otherwise, call (next-buffer)."
  (interactive)
  (if (and (boundp tabbar-mode) tabbar-mode)
      (tabbar-forward)
     (next-buffer)
))

by

(defun next-tab-or-buffer ()
  "Call (tabbar-forward) if tabbar-mode is on; otherwise, call (next-buffer)."
  (interactive)
  (if (and (boundp tabbar-mode) tabbar-mode)
      (tabbar-forward)
        (select-frame-set-input-focus  (next-frame))
))

**Comment by davidswelt** [comment] 2012-01-19 12:58
On Jan 19, 2012, at 7:54 AM, podczeck wrote:

> (defun next-tab-or-buffer ()
>  "Call (tabbar-forward) if tabbar-mode is on; otherwise, call (next-buffer)."
>  (interactive)
>  (if (and (boundp tabbar-mode) tabbar-mode)
>      (tabbar-forward)
>        (select-frame-set-input-focus  (next-frame))
> ))

Did you try this?
I don't see how it would work - next-frame throws the error because the window is dedicated.

**Comment by podczeck** [comment] 2012-01-19 16:11
Yes I tried, and I didn't get the dedicated window error message. However it does not work properly: It just cycles between frames, but even with one-buffer-one-frame mode, one could have several buffers in the same frame, and there is no cycling across  such buffers.

Am 19.01.2012 um 13:58 schrieb David Reitter:

**Comment by treese** [comment] 2021-01-22 18:39
This is an old bug, and things may have changed, but in Aquamacs 3.5, at least, I'm not sure why the `*Messages*` buffer is getting marked as dedicated. Everything else works as expected, and it seems appropriate that the commands don't do anything on a dedicated window.

At this point, it doesn't seem worth further work in the odd case of `*Messages*`, so I'm closing it. If it's a deeper problem, please reopen the bug.

**Closed as completed by treese** 2021-01-22 18:39 UTC
