### ISSUE TITLE
tabbar blinks when stepping in edebug mode

### ISSUE THREAD

**Issue by nathaniel** [aquamacs-emacs/aquamacs-emacs#27] opened 2010-05-15 04:11 UTC
With tabs on, in a window showing an edebug buffer only (no tabbar), stepping through the code when edebugging causes the tabbar to blink briefly into existence at each step.

**Comment by davidswelt** [comment] 2010-05-20 14:20
I've seen this many times, but can't reproduce any more.  Do you have a recipe?

**Comment by nathaniel** [comment] 2010-05-24 15:25
To reproduce:
Launch without customizations.
In _scratch_, paste and evaluate the following function definition:

(defun test-fun ()
       (print "line1") 
       (print "line1") 
       (print "line1") 
       (print "line1") 
       (print "line1") 
       (print "line1") 
       (print "line1") 
       (print "line1") 
       (print "line1") 
       (print "line1") 
       (print "line1"))

M-x emacs-lisp-mode for this buffer, then instrument this function for edebug (C-u C-M-x).

Cmd-t for new tab.  There, type and evaluate the expression: (test-fun).  Stepping through function with edebug exhibits blinking tabbar.

**Comment by davidswelt** [comment] 2010-05-24 15:42
Thanks.  That reproduces it for me.

Is it possible that edebug switches over to the other buffer in the edebug window itself, temporarily?  Would tabbar update at that point?

**Comment by davidswelt** [comment] 2010-05-24 15:45
Yeah, so this seems to help:

(setq tabbar-display-bug-workaround nil)

I suspect we might not need this workaround any longer.  It was developed during Carbon times, wasn't it?

**Comment by nathaniel** [comment] 2010-05-25 14:41
Yes, I'm sure this was added during carbon times.  turning off tabbar-display-bug-workaround works well for me -- no blinking tabbar, and no other side effects I've noticed so far.

**Comment by davidswelt** [comment] 2010-05-25 16:33
Switch off tabbar-display-bug-workaround.

Closed by 53b37d343b324201f9007b81e7cbe98fef65b9f9

**Closed as completed by davidswelt** 2010-05-25 16:33 UTC
